Repository 4GeeksAcademy/sp54-final-project-g4, pull requests merged in 2024-04, with the labels that each got.

#15 feat: buscador
  src/front/js/Layout.jsx
  src/front/js/pages/Buscador.jsx
Labels: enhancement

#16 Carrousel
  src/front/js/Layout.jsx
  src/front/js/component/Carroussel.jsx
Labels: enhancement

#17 Fix develop
  .env.example
  .vscode/settings.json
  docs/API_Documentation.md
  src/api/routes.py
  src/front/js/component/Login.jsx
  src/front/js/component/Navigation.jsx
  src/front/js/component/Signup.jsx
  src/front/js/store/appContext.js
  src/front/js/store/flux.js
Labels: bug fix, enhancement

#27 Review
  src/front/js/component/Review.jsx
Labels: enhancement

#28 feat:404
  src/front/js/pages/404.jsx
  src/front/styles/home.css
Labels: enhancement

#33 feat: settings
  .vscode/settings.json
  src/front/js/component/Settings.jsx
Labels: bug fix

#34 feat: profile view
  package-lock.json
  package.json
  src/api/models.py
  src/front/js/Layout.jsx
  src/front/js/component/Settings.jsx
  src/front/js/pages/Profile.jsx
  src/front/js/store/flux.js
Labels: bug fix, enhancement

#37 added bio to models
  src/api/models.py
Labels: bug fix

#36 feat: MovieDetails
  .devcontainer/devcontainer.json
  src/front/js/Layout.jsx
  src/front/js/component/Login.jsx
  src/front/js/component/ReviewModal.jsx
  src/front/js/component/Signup.jsx
  src/front/js/component/Spinner.jsx
  src/front/js/pages/MovieInfo.jsx
Labels: bug fix, enhancement

#35 wip:Faltan varias funcionalidades
  src/front/js/pages/Playlist.jsx
Labels: enhancement

#39 Fixed #23
  docs/API_Documentation.md
  src/api/models.py
  src/api/routes.py
  src/front/js/store/flux.js
Labels: bug fix

#42 wip:Falta terminar PUT y falta privacy setting
  src/front/js/component/Settings.jsx
  src/front/js/pages/Profile.jsx
Labels: bug fix, enhancement

#44 Temporal for showing to Eli
  src/front/img/Star-trail.png
  src/front/js/Layout.jsx
  src/front/js/component/Navigation.jsx
  src/front/js/component/Signup.jsx
  src/front/js/pages/Movies.jsx
Labels: bug fix, Deploy

#45 Wip: para enseñar a Hector
  src/front/js/component/Settings.jsx
Labels: bug fix, Deploy

#50 Add password confirmation modal and check-password endpoint
  src/api/routes.py
  src/front/js/component/ModalConfirmPassword.jsx
  src/front/js/component/ModalPassword.jsx
  src/front/js/component/Settings.jsx
  src/front/js/store/flux.js
Labels: bug fix

#51 fix: Settings also ask for password confirm
  src/front/js/component/Settings.jsx
Labels: bug fix

#52 feat/fix: Deploy requirements
  migrations/versions/53c63509e107_.py
  package-lock.json
  package.json
  src/api/models.py
  src/api/routes.py
  src/front/js/Layout.jsx
  src/front/js/component/Carrousel.jsx
  src/front/js/component/Footer.jsx
  src/front/js/component/Login.jsx
  src/front/js/component/ModalConfirmPassword.jsx
  src/front/js/component/ModalPassword.jsx
  src/front/js/component/Navigation.jsx
  src/front/js/component/Notification.jsx
  src/front/js/component/Review.jsx
  src/front/js/component/ReviewModal.jsx
  src/front/js/component/Settings.jsx
  src/front/js/pages/404.jsx
  src/front/js/pages/Home.jsx
  src/front/js/pages/MovieInfo.jsx
  src/front/js/pages/Movies.jsx
  src/front/js/pages/Profile.jsx
  src/front/js/store/appContext.js
  src/front/js/store/flux.js
  src/front/styles/home.css
Labels: bug fix, enhancement, Deploy

#53 First Deploy
  .devcontainer/devcontainer.json
  .env.example
  .vscode/settings.json
  Pipfile
  Pipfile.lock
  docs/API_Documentation.md
  migrations/env.py
  migrations/versions/53c63509e107_.py
  package-lock.json
  package.json
  src/api/admin.py
  src/api/models.py
  src/api/routes.py
  src/app.py
  src/front/img/Star-trail.png
  src/front/js/Layout.jsx
  src/front/js/component/Carrousel.jsx
  src/front/js/component/Footer.jsx
  src/front/js/component/Login.jsx
  src/front/js/component/ModalConfirmPassword.jsx
  src/front/js/component/ModalPassword.jsx
  src/front/js/component/ModalReport.jsx
  src/front/js/component/NavAndTab.jsx
  src/front/js/component/Navigation.jsx
  src/front/js/component/Notification.jsx
  src/front/js/component/Review.jsx
  src/front/js/component/ReviewModal.jsx
  src/front/js/component/Settings.jsx
  src/front/js/component/Signup.jsx
  src/front/js/component/Spinner.jsx
  src/front/js/pages/404.jsx
  src/front/js/pages/Buscador.jsx
  src/front/js/pages/Followers.jsx
  src/front/js/pages/Following.jsx
  src/front/js/pages/Home.jsx
  src/front/js/pages/MovieInfo.jsx
  src/front/js/pages/Movies.jsx
  src/front/js/pages/Playlist.jsx
  src/front/js/pages/Profile.jsx
  src/front/js/store/appContext.js
  src/front/js/store/flux.js
  src/front/styles/home.css
  template.html
Labels: Deploy

#54 Delete migrations/versions/9afef157fb85_.py
  migrations/versions/9afef157fb85_.py
Labels: Deploy

#58 fix: Deploy #2
  .vscode/settings.json
  package-lock.json
  package.json
  src/api/models.py
  src/api/routes.py
  src/front/js/component/Navigation.jsx
  src/front/js/component/Notification.jsx
  src/front/js/component/Review.jsx
  src/front/js/component/Settings.jsx
  src/front/js/pages/Home.jsx
  src/front/js/pages/MovieInfo.jsx
  src/front/js/pages/Profile.jsx
Labels: bug fix, enhancement, Deploy

#59 css casi hecho
  src/front/js/pages/Home.jsx
  src/front/js/pages/MovieInfo.jsx
  src/front/js/pages/Movies.jsx
  src/front/js/pages/Profile.jsx
  src/front/styles/index.css
Labels: bug fix, Deploy

#61 feat: review.jsx
  src/front/js/component/Review.jsx
  src/front/js/component/ReviewModal.jsx
  src/front/js/store/flux.js
Labels: bug fix

#63 Carlos deploy #2
  .env.example
  .vscode/settings.json
  Pipfile
  Pipfile.lock
  package-lock.json
  package.json
  src/api/models.py
  src/api/routes.py
  src/api/templates/confirm_email.html
  src/api/templates/reset_password.html
  src/app.py
  src/front/js/Layout.jsx
  src/front/js/component/Footer.jsx
  src/front/js/component/Login.jsx
  src/front/js/component/ModalConfirmPassword.jsx
  src/front/js/component/ModalForgotPassword.jsx
  src/front/js/component/Navigation.jsx
  src/front/js/component/Notification.jsx
  src/front/js/component/Review.jsx
  src/front/js/component/ReviewModal.jsx
  src/front/js/component/Settings.jsx
  src/front/js/component/Spinner.jsx
  src/front/js/pages/Home.jsx
  src/front/js/pages/License.jsx
  src/front/js/pages/MovieInfo.jsx
  src/front/js/pages/Movies.jsx
  src/front/js/pages/Profile.jsx
  src/front/js/store/flux.js
  src/front/styles/index.css
Labels: enhancement, Deploy

#64 fix: gold-route-hotfix deploy
  src/front/js/component/Review.jsx
  src/front/js/component/ReviewModal.jsx
Labels: bug fix, Deploy
