Repository 4GeeksAcademy/sp54-final-project-g4, pull requests merged in 2024-03, with the labels that each got.

#1 Feature: Models.py
  migrations/versions/596ea9aa6bd3_.py
  migrations/versions/72938cf01670_.py
  migrations/versions/9afef157fb85_.py
  package-lock.json
  src/api/models.py
Labels: enhancement

#2 feat: Full database
  src/api/admin.py
  src/api/models.py
Labels: bug

#3 wip: navbar
  .vscode/settings.json
  package-lock.json
  package.json
  src/front/js/Layout.jsx
  src/front/js/component/Navbar.jsx
  src/front/js/store/flux.js
Labels: enhancement

#5 API endpoints and documentation
  .env.example
  Pipfile
  Pipfile.lock
  docs/API_Documentation.md
  migrations/env.py
  package-lock.json
  src/api/admin.py
  src/api/models.py
  src/api/routes.py
  src/app.py
  src/front/js/Layout.jsx
  template.html
Labels: bug, enhancement

#6 feat: Footer
  src/front/js/component/Footer.jsx
Labels: enhancement

#9 feat: Navbar
  src/front/js/Layout.jsx
  src/front/js/component/Login.jsx
  src/front/js/component/Navbar.jsx
  src/front/js/component/Signup.jsx
  src/front/js/store/flux.js
Labels: enhancement

#7 feat: Profile
  src/front/js/Layout.jsx
  src/front/js/pages/Profile.jsx
Labels: enhancement

#11 wip:home
  src/front/js/pages/Home.jsx
Labels: enhancement

#12 Fix: Develop branch
  src/front/js/Layout.jsx
  src/front/js/component/Navigation.jsx
Labels: bug fix, enhancement
